### ISSUE TITLE
redux-thunk

### ISSUE THREAD

**Issue by fender** [Lullabot/React-Redux-Boilerplate#20]
Similarly to #19, do you see use-cases for thunk? Seems like quite a specific library to be using in a boilerplate.

**Comment by j-hannah** [comment]
I think the way you've suggested is a good approach. The advantage I see to leaving the API calls in the action creators is being able to retain the Redux docs as a solid reference. I think it potentially makes the project more useful to people who are just getting started with Redux. Are you cool with leaving it as is?

**Comment by fender** [comment]
@j-hannah It's totally up to you. I don't think there is a right or wrong way here.

Personally, I do think that if your goal is to follow the Redux docs and create something familiar, then I would suggest going with basic Actions as opposed to Action Creators (a slightly more advanced concept). I can see Action Creators being useful when you've got a large codebase where you are constantly dispatching the same actions from different places. I always prefer to start small and basic and then scale when/if necessary.

Some interesting reads in the docs:
* http://redux.js.org/docs/basics/Actions.html
* http://redux.js.org/docs/recipes/ReducingBoilerplate.html
* https://github.com/acdlite/flux-standard-action (Redux recommended way to build actions)

**Comment by j-hannah** [comment]
OK, thanks, @fender. I'll take a look at those. 👍
